[workspace]
resolver = "2"
members = [
    "demo",
    "inputs"
]

[workspace.package]
rust-version = "1.80.0"

[workspace.dependencies]
inputs = { path = "./inputs" }
demo = { path = "./demo" }

leptos = { version = "0.6" }
leptos_meta = { version = "0.6" }
leptos_router = { version = "0.6" }
